version: "3.8"

services:
  dunime_app:
    image: dunime_app_image
    container_name: dunime_app_container
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - dunime_db
    volumes:
      - ./.env:/app/.env

  dunime_db:
    image: mariadb:11.4.5
    container_name: dunime_db_container
    env_file:
      - .env
    volumes:
      - dunime_db_data:/var/lib/mysql  # path ini seharusnya /var/lib/mysql, bukan /var/lib/mariadb/data
    ports:
      - "3308:3306"

volumes:
  dunime_db_data:
