version: '3.8'

services:
  app:
    image: dunglas/frankenphp
    container_name: dunime-app
    working_dir: /app
    volumes:
      - ./src:/app
      - ./src/.env:/app/.env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: dunime-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: dunime-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
