services:
  app:
    build: .
    container_name: dunime-app
    ports:
      - "8080:80"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:11.4.5
    container_name: dunime-db
    restart: always
    ports:
      - "33060:3306" # HostPort:ContainerPort
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  db_data:
